@echo off
echo [CLIP-AI] Memulai Ultimate AI Clipper Pipeline...
echo [CLIP-AI] Memastikan dependensi terinstal...
pip install -r requirements.txt

echo [CLIP-AI] Menjalankan Worker Celery...
start "Celery Worker" cmd /k "venv\Scripts\activate && celery -A worker:celery_app worker --loglevel=info -P solo"

echo [CLIP-AI] Menjalankan Dashboard Flower (Monitoring)...
start "Flower" cmd /k "venv\Scripts\activate && celery -A worker:celery_app flower"

echo [CLIP-AI] Menjalankan API Server (FastAPI)...
venv\Scripts\activate && uvicorn main:app --reload --port 8000

pause
